version: "3.6"

services:

  music:
    image: ghcr.io/danielkoomen/webapp
    # build: .
    volumes:
      - type: bind
        source: ./music
        target: /music
      - type: bind
        source: ./data
        target: /data
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 128M
    # user: '1000' # optionally, change user id
    read_only: true
    cap_drop: ['all']
    environment:
      TZ: Europe/Amsterdam
      MUSIC_PROXIES_X_FORWARDED_FOR: 1

  music-nginx:
    image: ghcr.io/danielkoomen/webapp:nginx
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    user: "1000"
    environment:
      TZ: Europe/Amsterdam
      BACKEND_ADDRESS: http://music:8080
