version: "3.6"

services:

  music:
    ports:
      - 8080:8080
    build: .
    volumes:
      - type: bind
        source: ./music
        target: /music
      - type: bind
        source: ./data
        target: /data
      # To get new files without re-building, during development
      - type: bind
        source: ./src
        target: /app
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 128M
    user: "1000"
    read_only: true
    cap_drop: ['all']
    environment:
      TZ: Europe/Amsterdam
      MUSIC_ENV: dev
